services:
  redis_clone:
    build:
      context: .
      dockerfile: Dockerfile.redis
    ports:
      - "31337:31337"
    environment:
      REDIS_BIND_HOST: 0.0.0.0
      REDIS_PORT: 31337
      AOF_FILE: /app/data/appendonly.aof
    volumes:
      - .:/app
      - redis_data:/app/data
    command: sh -c "watchfiles --filter python 'python server.py' ."

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      - redis_clone
    environment:
      REDIS_HOST: redis_clone
      REDIS_PORT: 31337
    volumes:
      - .:/app
    command: ["uvicorn", "fastapi_cache.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
  
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - redis_clone
    environment:
      REDIS_HOST: redis_clone
      REDIS_PORT: 31337
    volumes:
      - .:/app
    command: ["python", "worker.py"]
volumes:
  redis_data: