FROM python:3.11-slim

WORKDIR /app

COPY requirements-worker.txt .

RUN pip install --no-cache-dir \
    --index-url https://download.pytorch.org/whl/cpu \
    torch==2.3.1 \
    && pip install --no-cache-dir -r requirements-worker.txt

COPY . .

CMD ["python", "-m", "worker.worker"]